document.writeln("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> ");
document.writeln("<html xmlns=\"http://www.w3.org/1999/xhtml\"> ");
document.writeln("<head> ");
document.writeln("<meta http-equiv=\"content-Type\" content=\"text/html;charset=gb2312\"> ");
document.writeln("<style type=\"text/css\"> ");
document.writeln("body{");
document.writeln("	margin:0 auto;");
document.writeln("}");
document.writeln(".menu { ");
document.writeln("font: 15px \"微软雅黑\", arial, Helvetica, sans-serif;");
document.writeln("font-weight:500;");
document.writeln("width:800px; ");
document.writeln("margin:0; ");
document.writeln("margin:0px 0; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul { ");
document.writeln("padding:0; ");
document.writeln("margin:0; ");
document.writeln("list-style-type: none; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li { ");
document.writeln("float:left; ");
document.writeln("position:relative; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li a, .menu ul li a:visited { ");
document.writeln("display:block; ");
document.writeln("text-align:center; ");
document.writeln("text-decoration:none; ");
document.writeln("width:113px; ");
document.writeln("height:70px; ");
document.writeln("color:#ffffff; ");
document.writeln("border:0px solid #fff; ");
document.writeln("border-width:0px 0px 0 0; ");
document.writeln("background:#0a70b1; ");
document.writeln("line-height:70px; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln("");
document.writeln(".menu ul li ul { ");
document.writeln("display: none; ");
document.writeln("z-index:999;");
document.writeln("}  ");
document.writeln(".menu ul li:hover a { ");
document.writeln("color:#fff; ");
document.writeln("background:#1986cb; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li:hover ul { ");
document.writeln("display:block; ");
document.writeln("position:absolute; ");
document.writeln("top:70px; ");
document.writeln("left:0; ");
document.writeln("width:113px; ");
document.writeln("height:50px;");
document.writeln("line-height:50px; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li:hover ul li a { ");
document.writeln("display:block; ");
document.writeln("background:#0a70b1; ");
document.writeln("color:#ffffff; ");
document.writeln("height:50px;");
document.writeln("line-height:50px;");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li:hover ul li a:hover { ");
document.writeln("background:#1986cb; ");
document.writeln("color:#ffffff; ");
document.writeln("height:50px;");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln("</style> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<style type=\"text/css\"> ");
document.writeln("table { ");
document.writeln("border-collapse:collapse; ");
document.writeln("margin:0; ");
document.writeln("padding:0; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li a.hide, .menu ul li a:visited.hide { ");
document.writeln("display:none; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li a:hover { ");
document.writeln("color:#fff; ");
document.writeln("background:#1986cb; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li a:hover ul { ");
document.writeln("display:block; ");
document.writeln("position:absolute; ");
document.writeln("top:70px; ");
document.writeln("left:0; ");
document.writeln("width:113px; ");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li a:hover ul li a { ");
document.writeln("background:#0a70b1; ");
document.writeln("color:#ffffff; ");
document.writeln("height:50px;");
document.writeln("line-height:50px;");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln(".menu ul li a:hover ul li a:hover { ");
document.writeln("background:#1986cb; ");
document.writeln("color:#ffffff; ");
document.writeln("height:50px;");
document.writeln("line-height:50px;");
document.writeln("z-index:999;");
document.writeln("} ");
document.writeln("</style> ");
document.writeln("<![endif]--> ");
document.writeln("</head> ");
document.writeln("<body> ");
document.writeln("<div class=\"menu\"> ");
document.writeln("<ul> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/system\">系统配置</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/system\">系统配置");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<ul> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/system/centos\">CentOS</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/system/rhel\">RHEL</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/system/ubuntu\">Ubuntu</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/system/debian\">Debian</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/system/other-system\">其它系统</a></li> ");
document.writeln("</ul> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/config\">环境部署</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/config\">环境部署 ");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<ul> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/config/web\">Web服务器</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/config/database\">数据库</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/other-config\">其它环境</a></li> ");
document.writeln("</ul> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/security\">安全优化</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/security\">安全优化");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/backup\">数据备份</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/backup\">数据备份 ");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<ul> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/backup/rsync\">Rsync</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/backup/inotify\">Inotify</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/backup/script\">备份脚本</a></li> ");
document.writeln("</ul> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/framework\">集群架构</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/framework\">集群架构 ");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<ul> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/framework/master-slave\">主从架构</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/framework/load-balancing\">负载均衡</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/framework/virtualization\">虚拟化</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/framework/cloud\">云计算</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/framework/bigdata\">大数据</a></li> ");
document.writeln("</ul> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/monitor\">运维监控</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/monitor\">运维监控");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<ul> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/monitor/zabbix\">Zabbix</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/monitor/cacti\">Cacti</a></li>");
document.writeln("</ul> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("<li><a class=\"hide\" href=\"http://www.osyunwei.com/archives/category/network\">网络管理</a> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("<a href=\"http://www.osyunwei.com/archives/category/network\">网络管理 ");
document.writeln("<table><tr><td> ");
document.writeln("<![endif]--> ");
document.writeln("<ul> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/network/network-devices\">网络设备</a></li> ");
document.writeln("<li><a href=\"http://www.osyunwei.com/archives/category/network/lan\">企业网络</a></li> ");
document.writeln("</ul> ");
document.writeln("<!--[if lte IE 6]> ");
document.writeln("</td></tr></table> ");
document.writeln("</a> ");
document.writeln("<![endif]--> ");
document.writeln("</li> ");
document.writeln("</ul> ");
document.writeln("<!-- clear the floats if required --> ");
document.writeln("<div class=\"clear\"> </div> ");
document.writeln("</div> ");
document.writeln("</body> ");
document.writeln("</html> ");
document.writeln("");